Repository Hackthon-2020/SANPAI, pull requests merged in 2020-12, with the labels that each got.

#4 Feat/#3 implement rooting
  package-lock.json
  package.json
  src/App.js
  src/components/pages/home/index.js
  src/components/pages/omikuji/index.js
  src/components/pages/shrine/index.js
  src/components/routing/navigation.js
  src/components/routing/route.js
Labels: enhancement

#10 Feat/#5 views
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/assets/img/back.png
  src/assets/img/choose.png
  src/assets/img/forest.jpg
  src/assets/img/hand.png
  src/assets/img/omikuji/omikuji-box.png
  src/assets/img/omikuji/omikuji-char.png
  src/assets/img/omikuji/result-char.png
  src/assets/img/osaisen/coin-10yen.png
  src/assets/img/osaisen/coin-1yen.png
  src/assets/img/osaisen/coin-500yen.png
  src/assets/img/osaisen/coin-50yen.png
  src/assets/img/osaisen/coin-5yen.png
  src/assets/img/osaisen/offertory-box.png
  src/assets/img/osaisen/osaisen-char.png
  src/assets/img/osaisen/suzu.png
  src/assets/img/osaisen/throw-char.png
  src/assets/img/osaisen/torii.png
  src/assets/img/san-char.png
  src/assets/img/sanpai-char.png
  src/assets/img/sanpai-logo-85*48.png
  src/assets/img/sanpai-logo.png
  src/components/card/cardList/index.jsx
  src/components/card/imgCard/index.jsx
  src/components/pages/home/index.css
  src/components/pages/home/index.jsx
  src/components/pages/omikuji/index.css
  src/components/pages/omikuji/index.jsx
  src/components/pages/sanpai/index.css
  src/components/pages/sanpai/index.jsx
  src/components/pages/shrine/index.css
  src/components/pages/shrine/index.jsx
  src/components/routing/navigation.js
  src/components/routing/navigation/index.css
  src/components/routing/navigation/index.jsx
  src/components/routing/route/index.jsx
Labels: enhancement

#13 Feat/#11 add footer
  public/index.html
  src/components/routing/navigation/index.jsx
  src/index.css
Labels: enhancement

#24 Feat/#12 implement select shrine
  package-lock.json
  package.json
  src/assets/img/back 2.png
  src/assets/img/choose 2.png
  src/assets/img/forest 2.jpg
  src/assets/img/hand 2.png
  src/assets/img/omikuji/omikuji-box 2.png
  src/assets/img/omikuji/omikuji-char 2.png
  src/assets/img/omikuji/result-char 2.png
  src/assets/img/osaisen/coin-10yen 2.png
  src/assets/img/osaisen/coin-1yen 2.png
  src/assets/img/osaisen/coin-500yen 2.png
  src/assets/img/osaisen/coin-50yen 2.png
  src/assets/img/osaisen/coin-5yen 2.png
  src/assets/img/osaisen/offertory-box 2.png
  src/assets/img/osaisen/osaisen-char 2.png
  src/assets/img/osaisen/suzu 2.png
  src/assets/img/osaisen/throw-char 2.png
  src/assets/img/osaisen/torii 2.png
  src/assets/img/san-char 2.png
  src/assets/img/sanpai-char 2.png
  src/assets/img/sanpai-logo 2.png
  src/assets/img/sanpai-logo-85*48 2.png
  src/assets/img/shrine/dazaifu.jpg
  src/assets/img/shrine/inari.jpg
  src/assets/img/shrine/isejin.webp
  src/assets/img/shrine/izumo.jpg
  src/assets/img/shrine/miyajidake.jpg
  src/assets/img/shrine/miyajima.jpg
  src/assets/img/shrine/munakata.jpg
  src/assets/img/shrine/okinosima.jpg
  src/components/card/cardList/index.jsx
  src/components/card/imgCard/index.jsx
  src/components/card/shrineCard/index.jsx
  src/components/modal/dialog.jsx
  src/components/pages/home/index.css
  src/components/pages/home/index.jsx
  src/components/pages/omikuji/index.jsx
  src/components/pages/shrine/index.jsx
  src/components/routing/route/index.jsx
Labels: enhancement

#29 Feat/#16 implement back button
  src/components/pages/omikuji/index.css
  src/components/pages/omikuji/index.jsx
  src/components/pages/omikuji/omikujiPlay.jsx
  src/components/pages/osaisen/index.css
  src/components/pages/osaisen/index.jsx
  src/components/pages/shrine/index.css
  src/components/pages/shrine/index.jsx
Labels: enhancement

#30 Issue/#27 fix
  src/assets/img/shrine/kamado.jpg
  src/assets/img/shrine/kitano.jpg
  src/components/card/cardList/index.jsx
  src/components/card/imgCard/index.jsx
  src/components/card/shrineCard/index.jsx
  src/components/modal/dialog.jsx
  src/components/pages/omikuji/index.jsx
  src/components/pages/omikuji/omikujiFunctions/omikujiPlay.jsx
  src/components/pages/omikuji/omikujiFunctions/setOmikuji.jsx
  src/components/pages/omikuji/omikujiFunctions/setOmikujiMsg.jsx
  src/components/pages/osaisen/index.jsx
  src/components/pages/osaisen/payment/index.css
  src/components/pages/osaisen/payment/index.jsx
  src/components/pages/payment/index.css
  src/components/pages/payment/index.jsx
  src/components/routing/footer/index.css
  src/components/routing/footer/index.jsx
  src/components/routing/route/index.jsx
Labels: bug

#35 おみくじmodalの修正 #34
  src/components/pages/omikuji/index.css
  src/components/pages/omikuji/omikujiFunctions/omikujiPlay.jsx
Labels: bug

#37 readmeの更新 #36
  README.md
Labels: documentation
